### ISSUE TITLE
java.lang.NoClassDefFoundError: org/slf4j/MDC$MDCCloseable

### ISSUE THREAD

**Issue by Kaktushose** [Kaktushose/levelbot2#34]
**Beschreibe den Bug**
java.lang.NoClassDefFoundError: org/slf4j/MDC$MDCCloseable
        at net.dv8tion.jda.internal.requests.WebSocketClient.reconnect(WebSocketClient.java:522)
        at net.dv8tion.jda.internal.requests.WebSocketClient$ReconnectNode.run(WebSocketClient.java:1294)
        at net.dv8tion.jda.api.utils.SessionControllerAdapter$QueueWorker.processQueue(SessionControllerAdapter.java:220)
        at net.dv8tion.jda.api.utils.SessionControllerAdapter$QueueWorker.run(SessionControllerAdapter.java:203)
Caused by: java.lang.ClassNotFoundException: org.slf4j.MDC$MDCCloseable
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
        ... 4 common frames omitted

**Comment by Kaktushose** [comment]
slf4j war veraltet, fehler behoben
